version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.9.0
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"variables\":[],\"name\":\"public\"}]"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.1
    volumes:
      - ./config/dispatcher:/config
  frontend:
    image: kanselarij/frontend-themis:0.3.1
  database:
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      DATABASE_COMPATIBILITY: "Virtuoso"
      DATABASE_OVERLOAD_RECOVERY: "on"
    volumes:
      - ./config/authorization:/config
  delta-notifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/public"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
  resource:
    image: semtech/mu-cl-resources:1.20.0
    volumes:
      - ./config/resources:/config
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
  file:
    image: semtech/mu-file-service:3.1.2
    volumes:
      - ./data/files:/share
  uri-info:
    image: redpencil/mu-uri-info-service
  resource-labels:
    image: lblod/resource-label-service:0.0.3
  publication-consumer:
    image: kanselarij/valvas-publication-consumer:themis
    volumes:
      - ./data/downloaded-publications:/tmp
      - ./data/files:/share
